//JS課題
//try catchを使ってエラー文をコンソールに表示させる

let array = [0,1,2,3,4];

try{
    for(let i = 0; i <= 5; i++){
        console.log(array2[i]);
    }
} catch(e){
    console.log("エラーを検知しました");
}